singleuser:
    lifecycleHooks:
        postStart:
            exec:
                command: ["/bin/bash", "-c", "/opt/ncar/scripts/initialize_tutorials"]
    image:
        name: docker.io/escomp/test-ctsm-cislcloud-v4
        tag: v17
    cpu:
      limit: 4
    memory:
      limit: 16G
    storage:
        capacity: 20Gi
        homeMountPath: /home/user
        dynamic:
            storageClass: ceph-kubepv
ingress:
    enabled: true
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 600m
        nginx.org/client-max-body-size: 10m
        nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/secure-backends: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/websocket-services: proxy-public
        nginx.org/websocket-services: proxy-public
        cert-manager.io/cluster-issuer: incommon
    ingressClassName: nginx-external
    hosts:
        - ncote-jhub.k8s.ucar.edu
    tls:
        - secretName: ncote-jhub-tls-cert
          hosts:
            - ncote-jhub.k8s.ucar.edu
hub:
    config:
        JupyterHub:
            authenticator_class: nativeauthenticator.NativeAuthenticator
        Authenticator:
            allow_all: true
            admin_users:
                - ncote
                - kcote
                - varshareddy
                - bdobbins
                - slevis
                - khrpcek
                - samrabin
        NativeAuthenticator:
            enable_signup: true
            minimum_password_length: 8
            check_common_password: true
            ask_email_on_signup: true
            allowed_failed_logins: 3
            seconds_before_next_try: 1200
      # Clone custom JupyterHub templates into a volume
    initContainers:
        - name: git-clone-templates
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --branch=master
            - --depth=1
            - --
            - https://github.com/NicholasCote/ncar-hub-homepage.git
            - /etc/jupyterhub/custom
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: custom-templates
              mountPath: /etc/jupyterhub/custom
    extraVolumes:
        - name: custom-templates
          emptyDir: {}
    extraVolumeMounts:
        - name: custom-templates
          mountPath: /etc/jupyterhub/custom
    extraConfig:
        templates: |
          c.JupyterHub.template_paths = ['/etc/jupyterhub/custom']
proxy:
    service:
        type: ClusterIP
